import * as DevIcons from "react-icons/si";

export const languageIconMap: Record<string, keyof typeof DevIcons> = {
  "javascript": "DiJavascript",
  "typescript": "DiTypescript",
  "html": "DiHtml5",
  "css": "DiCss3",
  "python": "DiPython",
  "java": "DiJava",
  "c": "DiC",
  "c++": "DiCplusplus",
  "csharp": "DiCsharp",
  "php": "DiPhp",
  "ruby": "DiRuby",
  "go": "DiGo",
  "rust": "DiRust",
  "swift": "DiSwift",
  "kotlin": "DiKotlin",
  "r": "DiR",
  "dart": "DiDart",
  "perl": "DiPerl",
  "bash": "DiTerminal",
  "shell": "DiTerminal",
  "sql": "DiDatabase",
  "lua": "DiLua",
  "matlab": "DiMatlab",
  "json": "DiJson",
  "xml": "DiXml",
  "yaml": "DiYaml",
};
