name: Tauri Build

on:
  push:
    tags:
      - 'v*' # Runs on version tags like v1.0.0
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: |
            x86_64-unknown-linux-gnu
            x86_64-apple-darwin
            x86_64-pc-windows-msvc

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libappindicator3-dev librsvg2-dev -y

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-build-${{ matrix.platform }}
          path: src-tauri/target/release/bundle/
